num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
print("Greater than:", num1 > num2)
print("Less than:", num1 < num2)
print("Equal to:", num1 == num2)
print("Not equal to:", num1 != num2)
print("Greater than or equal to:", num1 >= num2)
print("Less than or equal to:", num1 <= num2)
